# This is a kludge to ensure that builds on the main branch are run in commit order
# otherwise, there is a race condition where the snapshot release will be for an older commit

name: Build scheduler

on:
  push:
    branches: [ snapshot-release-2 ]
  workflow_dispatch:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ snapshot-release-2 ]
    types:
      - completed

concurrency: build_scheduler

jobs:
  build_scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v5
        with:
          script: |
            const script = require('.github/scripts/build_scheduler.js')
            await script({
              branchRef: "refs/heads/snapshot-release-2",
              markRef: "refs/tags/build_scheduler",
              workflowPath: ".github/workflows/ci.yml",
              workflowInputs: {
                publish_snapshot: "true",
              },
              context, core, github,
            })
