name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ snapshot-release-2 ]
    tags: [ v* ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  # We run the tests on many OS / Java combinations but also the Compile step because some users build
  # their own jars from source, so it is good for CI to check that is working on all combinations.
  build:
    if: "false"
#    if: "!( github.event_name == 'push' && startsWith(github.event.commits[0].message, '[maven-release-plugin] prepare release ') )"
    strategy:
      fail-fast: false
      matrix:
        #        java_version: [ 8, 11, 17 ]
        #        os: [ macos-10.15,  macos-11, ubuntu-18.04, ubuntu-20.04, windows-2016, windows-2019, windows-2022 ]
        include:
          - release_from_this_build: true
            os: ubuntu-20.04
            java_version: 8
    runs-on: ${{ matrix.os }}
    outputs:
      release_version: ${{ steps.configure_release.outputs.release_version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java_version }}
          distribution: temurin
          cache: maven

      # Downloading all the dependencies is very log spammy, so we do this in its own step.
      - name: Prime maven cache
        run: mvn --batch-mode dependency:go-offline

      - name: Set pom version for snapshot TODO
        if: matrix.release_from_this_build
        run: mvn versions:set "-DnewVersion=${GITHUB_SHA}"

      # Compile / Test / Package are separate steps so the reason for any failure is more obvious in GitHub UI
      - name: Compile
        run: mvn --batch-mode compile

      - name: Test
        run: mvn --batch-mode test

      # todo release here?
      - name: Package
        if: matrix.release_from_this_build
        run: mvn --batch-mode -Dmaven.test.skip=true package

      - name: Upload jar artifacts
        if: matrix.release_from_this_build
        uses: actions/upload-artifact@v2
        with:
          # Using github.run_number here to reduce confusion when downloading & comparing artifacts from several builds  
          name: ${{ github.run_number }}-jars
          path: target/*.jar

      - name: Deploy sha versioned package to Github Packages
        if: matrix.release_from_this_build && github.event_name == 'push' && github.ref == 'refs/heads/snapshot-release-2'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mvn --batch-mode package deploy:deploy \
            -DaltDeploymentRepository=github::https://maven.pkg.github.com/matthew16550/plantuml \
            -Dmaven.test.skip=true

      - name: Upload jar artifact (only simple jar - without javadoc or sources)
        if: ${{ matrix.release_from_this_build }}
        uses: actions/upload-artifact@v2
        with:
          name: plantuml-jar
          path: |
            target/*.jar
            !target/*-javadoc.jar
            !target/*-sources.jar

      - name: Configure release job
        id: configure_release
        if: matrix.release_from_this_build
        run: .github/scripts/configure_release_job.sh

  refresh_snapshot:
#    needs: [ build ]
    concurrency:
      group: refresh_snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: debug
        uses: actions/github-script@v5
        with:
          script: |
            try {
              const response = await github.rest.repos.getReleaseByTag({
                ...context.repo,
                tag: "snapshot",
              })
              console.log(response)
            } catch (error) {
              if (error.status === 404)
                return null;
              throw error
            }

      - name: Decide if the snapshot needs refreshing
        id: decide
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('.github/scripts/refresh_snapshot_decide.js')
            await script({context, core, github})

#      - name: Write .netrc file
#        if: steps.decide.outputs.new_sha
#        env:
#          LOGIN: ${{ github.repository_owner }}
#          PASSWORD: ${{ github.token }}
#        run: echo "machine maven.pkg.github.com login $LOGIN password $PASSWORD" >> ~/.netrc

      - name: Refresh snapshot release
        if: steps.decide.outputs.new_sha
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RELEASE_SHA: ${{ steps.config.outputs.new_sha }}
          REPO_OWNER: ${{ github.repository_owner }}
        run: .github/scripts/refresh_snapshot.sh

  release:
    needs: [ build ]
    if: needs.build.outputs.release_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Download jars
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.run_number }}-jars

      - name: Create release in GitHub
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RELEASE_VERSION: ${{ needs.build.outputs.release_version }}
          RELEASE_SHA: ${{ github.sha }}
          TAG: v${{ needs.build.outputs.release_version }}
        run: .github/scripts/release.sh
