name: CI

on:
  create:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Configure job
        id: config
        run: |
          # Debug Info
          # ==========
          # github.actor.id     : ${{ github.actor.id }}
          # github.event_name   : ${{ github.event_name }}
          # github.event.action : ${{ github.event.action }}
          # github.ref          : ${{ github.ref }}
          
          env
          
          if [[ '${{ github.ref }}' == refs/tags/v* ]]; then
            echo "::set-output name=do_release::true"
            echo "::set-output name=pom_version::$(echo '${{ github.ref }}' | cut -c 12-)"
          fi

      - name: Checkout the repository
        uses: actions/checkout@v2

      # GitHub will show this as the user if the workflow uploads any release assets or makes pushes etc.
      # See https://github.com/actions/checkout/issues/13#issuecomment-724415212
      - name: Configure git user
        run: |
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.name  'github-actions[bot]'
          
      - name: Set up java
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'

      # Downloading all the dependencies is very log spammy, so we do this in its own step.
      - name: Prime maven cache
        run: mvn --batch-mode dependency:go-offline

      # POM version is usually a -SNAPSHOT at this point, if this is a release then we set the version from the tag
      - name: Set POM version
        if: steps.config.outputs.do_release == 'true'
        run: |
          mvn --batch-mode versions:set '-DnewVersion=${{ steps.config.outputs.pom_version }}'

      # Compile / Test / Package are separate steps so the reason for any build failure is more obvious in GitHub UI
      - name: Compile
        run: mvn --batch-mode compile

      - name: Test
        run: mvn --batch-mode test

      - name: Package
        run: mvn --batch-mode -Dmaven.test.skip=true package
  
      - name: Create release in GitHub
        uses: softprops/action-gh-release@2d72d869af3bf23602f9593a1e3fd739b80ac1eb  # v0.1.12
        if: steps.config.outputs.do_release == 'true'
        with:
          discussion_category_name: Announcements
          fail_on_unmatched_files: true
          files: |
            target/plantuml-${{ steps.config.outputs.pom_version }}.jar
            target/plantuml-${{ steps.config.outputs.pom_version }}-javadoc.jar
            target/plantuml-${{ steps.config.outputs.pom_version }}-sources.jar
