name: Release Artifacts

on:
  release:
    types: [created]

env:
  RELEASE_TAG: ${{ github.event.release.tag_name }}
  
jobs:
  jar:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the released code
        uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ env.RELEASE_TAG }}
          
      - name: Configure Git
        run: |
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.name  'github-actions[bot]'
          
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Caching currently doesn't achieve anything here, I think because we have a tag checked out.
      # Hopefully someone at GitHub will fix it then caching will magically start working for us!
      # https://github.com/actions/cache/issues/556
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
        
      # Downloading all the dependencies is very log spammy so we do this in its own step
      - name: Download Maven Dependencies
        run: mvn --batch-mode dependency:go-offline
        
      # The POM version is usually a -SNAPSHOT at this point, we set it to the requested tag because it will be
      # present inside the JAR so should reflect the actual release tag.
      - name: Set POM version
        run: mvn --batch-mode versions:set "-DnewVersion=${RELEASE_TAG}"

      # We are not skipping tests here.  They are half redundant because tests also run in the CI build
      # but it's possible for a release to be accidentally created from a commit where tests do not pass so
      # running them again here is useful (they do not take up much time).
      #
      # This is a code smell suggesting the CI / Release process can be simplified.  But as a first attempt it is good enough :-)
      - name: Build JAR
        run: mvn --batch-mode -Dmaven.javadoc.skip=true -Dmaven.source.skip=true package

      # See https://docs.github.com/en/rest/reference/repos#upload-a-release-asset
      - name: Upload JAR
        run: |
          upload_url="$(echo '${{ github.event.release.upload_url }}' | sed 's/{.*//' )"
          curl \
            --silent \
            --url "${upload_url}?name=plantuml-${RELEASE_TAG}.jar" \
            --header 'Accept: application/vnd.github.v3+json' \
            --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Content-Type: application/java-archive' \
            --data-binary "@target/plantuml-${RELEASE_TAG}.jar"
