name: Update Snapshot Release

on:
  push:
    branches: [ snapshot-release-2 ]
  workflow_dispatch:
  workflow_run:
    workflows: [ CI ]
    branches: [ snapshot-release-2 ]
    types: [ completed ]

concurrency:
  group: update_snapshot_release
  cancel-in-progress: true

jobs:
  update_snapshot_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find artifact for snapshot release
        id: artifact
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('.github/scripts/find_artifact_for_snapshot_release.js')
            await script({context, core, github})

      - name: Download artifact
        if: steps.artifact.outputs.artifact_name
        env:
          ARTIFACT_NAME: ${{ steps.artifact.outputs.artifact_name }}
          GITHUB_TOKEN: ${{ github.token }}
          WORKFLOW_RUN_ID: ${{ steps.artifact.outputs.workflow_run_id }}
        run: gh run download "${WORKFLOW_RUN_ID}" -n "${ARTIFACT_NAME}"

      - name: Create snapshot release
        if: steps.artifact.outputs.artifact_name
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SHA: ${{ steps.artifact.outputs.sha }}
        run: .github/scripts/release_snapshot.sh
